### ISSUE TITLE
Criar interface gráfica 

### ISSUE THREAD

**Issue by igorpereirag** [Joseane107/Encoder_GrupoDeEstudos_PythonDoZero#3]
Podemos criar uma interface gráfica com HTML e css

**Comment by Joseane107** [comment]
> Podemos criar um interface gráfica com HTML e css

Sim, e dá para utilizar a mesma que você utilizou no código principal em Java? E podemos fazer algumas modificações, por exemplo, o layout (imagem de fundo, etc)
